name: countdown_app
description: "A beautiful countdown event app with shareable mini-pages."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  appwrite: ^12.0.3
  timezone: ^0.9.2
  intl: ^0.19.0
  uuid: ^4.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/themes/
    - assets/fonts/

  fonts:
    - family: PPObjectSans
      fonts:
        - asset: assets/fonts/PPObjectSans-Regular.otf
          weight: 400
        - asset: assets/fonts/PPObjectSans-Medium.otf
          weight: 500
        - asset: assets/fonts/PPObjectSans-Bold.otf
          weight: 700
